-- MySQL Script generated by MySQL Workbench
-- Пн 19 окт 2020 09:49:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mgol
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mgol
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mgol` ;
USE `mgol` ;

-- -----------------------------------------------------
-- Table `mgol`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mgol`.`role` (
  `id` INT NOT NULL DEFAULT 1,
  `name` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mgol`.`class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mgol`.`class` (
  `id` INT NOT NULL,
  `number` INT NULL,
  `letter` VARCHAR(45) NULL,
  `form_master` INT NOT NULL,
  PRIMARY KEY (`id`, `form_master`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_class_user1_idx` (`form_master` ASC) VISIBLE,
  CONSTRAINT `fk_class_user1`
    FOREIGN KEY (`form_master`)
    REFERENCES `mgol`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

ALTER TABLE mgol.class CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE mgol.class drop PRIMARY KEY, ADD PRIMARY KEY (id);
ALTER TABLE mgol.class MODIFY form_master INT NULL;


-- -----------------------------------------------------
-- Table `mgol`.`user_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mgol`.`user_status` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mgol`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mgol`.`user` (
  `id` INT NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `class_id` INT NULL,
  `user_status_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_status_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  INDEX `fk_user_class1_idx` (`class_id` ASC) VISIBLE,
  INDEX `fk_user_user_status1_idx` (`user_status_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_class1`
    FOREIGN KEY (`class_id`)
    REFERENCES `mgol`.`class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_user_status1`
    FOREIGN KEY (`user_status_id`)
    REFERENCES `mgol`.`user_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

ALTER TABLE mgol.user CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mgol`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mgol`.`user_role` (
  `user_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  INDEX `fk_user_role_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_user_role_role1_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_role_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mgol`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_role_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `mgol`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mgol`.`subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mgol`.`subject` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

ALTER TABLE `mgol`.`subject` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- -----------------------------------------------------
-- Table `mgol`.`period`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mgol`.`period` (
  `id` INT NOT NULL,
  `day_of_week` SMALLINT(1) NOT NULL,
  `start_time` TIME NOT NULL,
  `end_time` TIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mgol`.`class_schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mgol`.`class_schedule` (
  `id` INT NOT NULL,
  `teacher_id` INT NOT NULL,
  `room` INT NULL,
  `class_id` INT NOT NULL,
  `subject_id` INT NOT NULL,
  `period_id` INT NOT NULL,
  PRIMARY KEY (`id`, `teacher_id`, `class_id`, `subject_id`, `period_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_class_schedule_user1_idx` (`teacher_id` ASC) VISIBLE,
  INDEX `fk_class_schedule_class1_idx` (`class_id` ASC) VISIBLE,
  INDEX `fk_class_schedule_subject1_idx` (`subject_id` ASC) VISIBLE,
  INDEX `fk_class_schedule_period1_idx` (`period_id` ASC) VISIBLE,
  CONSTRAINT `fk_class_schedule_user1`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `mgol`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_class_schedule_class1`
    FOREIGN KEY (`class_id`)
    REFERENCES `mgol`.`class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_class_schedule_subject1`
    FOREIGN KEY (`subject_id`)
    REFERENCES `mgol`.`subject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_class_schedule_period1`
    FOREIGN KEY (`period_id`)
    REFERENCES `mgol`.`period` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mgol`.`reward`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mgol`.`reward` (
  `id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_reward_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_reward_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mgol`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mgol`.`notification_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mgol`.`notification_type` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'Type of notification: news, info, important';


-- -----------------------------------------------------
-- Table `mgol`.`notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mgol`.`notification` (
  `id` INT NOT NULL,
  `created_by` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `message` VARCHAR(45) NULL,
  `approver` INT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `is_approved` TINYINT NOT NULL DEFAULT 0,
  `notification_type_id` INT NOT NULL,
  PRIMARY KEY (`id`, `created_by`, `notification_type_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_notification_user1_idx` (`approver` ASC) VISIBLE,
  INDEX `fk_notification_notification_type1_idx` (`notification_type_id` ASC) VISIBLE,
  INDEX `fk_notification_user2_idx` (`created_by` ASC) VISIBLE,
  CONSTRAINT `fk_notification_user1`
    FOREIGN KEY (`approver`)
    REFERENCES `mgol`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notification_notification_type1`
    FOREIGN KEY (`notification_type_id`)
    REFERENCES `mgol`.`notification_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notification_user2`
    FOREIGN KEY (`created_by`)
    REFERENCES `mgol`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mgol`.`user_notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mgol`.`user_notification` (
  `user_id` INT NOT NULL,
  `notification_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `notification_id`),
  INDEX `fk_user_notification_notification1_idx` (`notification_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_notification_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mgol`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_notification_notification1`
    FOREIGN KEY (`notification_id`)
    REFERENCES `mgol`.`notification` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
