POST http://127.0.0.1:8080/classes
Content-Type: application/json

{
  "number": 9,
  "letter": "З",
  "formMaster": "6e5cd906-27e8-11eb-aa2f-0242ac140002",
  "classMonitor": "6e5cd906-27e8-11eb-aa2f-0242ac140002"
}